spring.application.name=ChatApplication
spring.data.mongodb.uri=mongodb+srv://hondahero503_db_user:Manjul1234@mychatcluster.hks21uq.mongodb.net/?appName=MyChatCluster
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

