spring.application.name=ChatApplication

# 1. Fixed MongoDB URI (Added /chatdb before the '?')
spring.data.mongodb.uri=mongodb+srv://hondahero503_db_user:Manjul1234@mychatcluster.hks21uq.mongodb.net/chatdb?appName=MyChatCluster

# 2. Render Port Binding Fix
server.port=${PORT:8080}

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false